### ISSUE TITLE
gdt2vdds: `thread 'main' panicked at src\bin\gdt2vdds.rs:72:52:`

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/gdt2dicom#49]
1. Running this `.\gdt2vdds.exe --gdt-file .\gdt\ --output .\jpeg2epat\ --bvs 3Shape`
2. I get: 
```
[2024-03-01T11:21:51Z INFO  gdt2vdds] Loading VDDS_MMI: C:\Windows\VDDS_MMI.INI
thread 'main' panicked at src\bin\gdt2vdds.rs:72:52:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by zdavatz** [comment]
```
[BVS]
NAME1=3Shape
[3Shape]
NAME=3Shape
VERSION=1.4
STAGES=123
PATDATIMPORT=C:\Program Files\3Shape\Dental Desktop\Plugins\ThreeShape.PracticeManagementIntegration\DentalDesktopCmd.exe
PATDATIMPORT_OS=1
PATDATIMPORT_EVENT=2
MMOINFEXPORT=C:\Program Files\3Shape\Dental Desktop\Plugins\ThreeShape.PracticeManagementIntegration\DentalDesktopCmd.exe
MMOINFEXPORT_OS=1
MMOEXPORT=C:\Program Files\3Shape\Dental Desktop\Plugins\ThreeShape.PracticeManagementIntegration\DentalDesktopCmd.exe
MMOEXPORT_OS=1
```
